name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v2
      with:
          name: app
          path: public